
package com.dingfan.webservice.client;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DingFanService", targetNamespace = "http://wwww.dingfan.org/webservice/DingFanWebService", wsdlLocation = "http://localhost:8080/DingFan/webservice/DingFanService?wsdl")
public class DingFanService
    extends Service
{

    private final static URL DINGFANSERVICE_WSDL_LOCATION;
    private final static WebServiceException DINGFANSERVICE_EXCEPTION;
    private final static QName DINGFANSERVICE_QNAME = new QName("http://wwww.dingfan.org/webservice/DingFanWebService", "DingFanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DingFan/webservice/DingFanService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DINGFANSERVICE_WSDL_LOCATION = url;
        DINGFANSERVICE_EXCEPTION = e;
    }

    public DingFanService() {
        super(__getWsdlLocation(), DINGFANSERVICE_QNAME);
    }

//    public DingFanService(WebServiceFeature... features) {
//        super(__getWsdlLocation(), DINGFANSERVICE_QNAME, features);
//    }
//
//    public DingFanService(URL wsdlLocation) {
//        super(wsdlLocation, DINGFANSERVICE_QNAME);
//    }
//
//    public DingFanService(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, DINGFANSERVICE_QNAME, features);
//    }
//
//    public DingFanService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public DingFanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns DingFanWebService
     */
    @WebEndpoint(name = "DingFanWebServicePort")
    public DingFanWebService getDingFanWebServicePort() {
        return super.getPort(new QName("http://wwww.dingfan.org/webservice/DingFanWebService", "DingFanWebServicePort"), DingFanWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DingFanWebService
     */
    @WebEndpoint(name = "DingFanWebServicePort")
    public DingFanWebService getDingFanWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wwww.dingfan.org/webservice/DingFanWebService", "DingFanWebServicePort"), DingFanWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DINGFANSERVICE_EXCEPTION!= null) {
            throw DINGFANSERVICE_EXCEPTION;
        }
        return DINGFANSERVICE_WSDL_LOCATION;
    }

}
